### PR TITLE
Sb 96 canvas task refresh

### PR DESCRIPTION
**Pull request by Alexander-Russakoff**
Added front end loading state and backend has been reworked to fully handle importing the canvas tasks. The tasks will be refreshed/updated if they already exist.

### CODE REVIEW

**Review by katrinajaneczko — CHANGES_REQUESTED** [review]
- I see that you added `received` and `unique_canvas_tag` to `models` and the `task` serializer. Solid.

- It seems like in `views`, you’re printing a lot to the terminal, is this all for error checking? did you want to merge these, or maybe make them into some kind of test later?

- LOVE the loading button!!! However I think you were so focused on putting the “i” before the “e” that you forgot the “v” entirely. Change the text from “Retrieing”—> “Retrieving”.

- I like that you redirect to the main page right after.

- Remember how we talked about making a silly little loading screen? I made one!

**Comment by katrinajaneczko** [comment]
Look at my PR into your branch that I just made. In it, I added a loading screen with a cute little spinning cat, and I corrected the spelling on “Retrieving” on the loading page.

**Review by katrinajaneczko — APPROVED** [review]
approving this on the contingency that you merge my branch into this one before merging to main

**Comment by Alexander-Russakoff** [comment]
I reviewed the PR. Everything looks great. This did introduce a small bug where the button was still clickable while the spinner was loading. I moved the button up to the portion of the div container that is controlled by the ternary operator so that it is no longer displayed at all while the loading spinner is active. Will approve changes and merge now

**Comment by katrinajaneczko** [comment]
you're the best. thank you

**Review by ccho-0508 — APPROVED** [review]

**Pull request merged**
