### PR TITLE
Cho frontend

### PR DESCRIPTION
**Pull request by ccho-0508**
login site + main site

### CODE REVIEW

**Comment by ccho-0508** [comment]
PLEAS EPLEAS EPLEASE PELASE

**Comment by Alexander-Russakoff** [comment]
best by test
beast by teast

**Review by Alexander-Russakoff — APPROVED** [review]
excellent

**Review by jay-newman — APPROVED** [review]
Lgtm. Live approval. Eggselent

**Comment by Parth099** [comment]
🥚

**Comment by jay-newman** [comment]
Don't comment on a PR again.

**Pull request merged**
