### PR TITLE
Added backend unit testing

### PR DESCRIPTION
**Pull request by jay-newman**

### CODE REVIEW

**Review by harrisonfedor — APPROVED** [review]
lgtm! we can go back and update format later in the sprint

**Comment by katrinajaneczko** [comment]
Hey, the content looks great but the deployment isn't going to work with the <br> tags (I've made this mistake many times). They all need to be changed to <br/>

**Review by katrinajaneczko — CHANGES_REQUESTED** [review]
The code will break with the \<br> tag, we need to replace it with the XHTML-friendly \<br/>

**Comment by harrisonfedor** [comment]
@katrinajaneczko 👑!

**Review by katrinajaneczko — APPROVED** [review]
I changed the \<br> tags\ issue and reviewed the tests -- all looks good!

**Pull request merged**
