### PR TITLE
Main Page Template

### PR DESCRIPTION
**Pull request by ccho-0508**
- Replaced front-end React application w/ the main page template

### CODE REVIEW

**Comment by jay-newman** [comment]
Looks great. Ran docker container and can see main page.

**Review by jay-newman — APPROVED** [review]
Looks great. Ran the docker container. Can see the amazing main page!

**Comment by katrinajaneczko** [comment]
Ran the Docker container. Page looks great. I especially enjoy the "WEIGHT: 5 Paper Clips". 
I can see the progress bar, a place for mood and weight, the pet name, and the dropdown for logout, settings, and Canvas integration. 
Thanks, Christine!

**Review by katrinajaneczko — APPROVED** [review]
Ran the Docker container. Page looks great. I especially enjoy the "WEIGHT: 5 Paper Clips".
I can see the progress bar, a place for mood and weight, the pet name, and the dropdown for logout, settings, and Canvas integration.
Thanks, Christine!

**Comment by katrinajaneczko** [comment]
:)

**Pull request merged**
