### PR TITLE
SB-45 account profile page

### PR DESCRIPTION
**Pull request by katrinajaneczko**
Account Page:
- user can see their username & email
- user can change their bio, birthday, name
- form validation exists

Header:
- username now displays in header
- Account added to header
- Home added to dropdown menu
- clicking on "My Study Buddy" opens Main too

Pet Profile Page
- created AvatarContext & handlers for avatarInfo & setAvatar (to use in PetProfPage)
- user can now change pet's name & bio

### CODE REVIEW

**Comment by Alexander-Russakoff** [comment]
Approved. 

Pages look good and appear to be functioning as intended. Would be nice to add a background color that matches or compliments the main page, and some styling to the forms, but we can make another ticket for that. For the flavour text, I do believe we decided we would assign an initial bio to each pet. However, I'm not apposed to letting the user change it.

**Comment by Alexander-Russakoff** [comment]
Actually I can't review this since I'm not in the requested list. I wasn't even aware it worked like. Do we want to do this going forward?

**Review by Alexander-Russakoff — APPROVED** [review]
Looks good! 

See previous comments

**Review by harrisonfedor — APPROVED** [review]
this all looks great kat! thank you so much for cleaning up the organization to reduce all of those duplicate calls we would have otherwise had. really nice stuff!

**Comment by katrinajaneczko** [comment]
@Alexander-Russakoff that sounds good, I also would like to add some styling but I agree that a new ticket would be good. Maybe that new ticket could be for cleaning up / creating consistency for the css/styling for the site as a whole? what do you think?

Additionally, before I merge, I am going to add a commit that gives the pet an initial flavour text that is changeable so it is consistent with what we previously discussed, as you pointed out.

As far as requesting review -- I didn't know it worked like that either to be honest. Let's discuss next scrum.

@harrisonfedor thanks for taking a look!

**Pull request merged**
