### PR TITLE
CSS for account and pet profile pages, SB-45 edit

### PR DESCRIPTION
**Pull request by katrinajaneczko**
As Alex suggested in my PR, I made the styling for PetProfPage and AccountPage consistent with the rest of the site.

### CODE REVIEW

**Review by ccho-0508 — APPROVED** [review]
thank you for adding the bootstrap components for consistency! My only comment would be centering the form fields in the account page but it's a small thing so you're good to go! Cheers

**Review by Alexander-Russakoff — CHANGES_REQUESTED** [review]
The forms are shaping up nicely! Would definitely approve this portion of the PR. 

However, the calendar page seems a little buggy. If I click a button corresponding to a specific day it crashes the whole site. Also, if it's only buttons in the react component, I might suggest we instead use a bootstrap calendar instead and list the task titles. They look really nice and clean, and are consistent with our other forms. I humbly request that we remove this for now and give this creating the calendar it's own ticket. 

https://mdbootstrap.com/docs/standard/plugins/calendar/

**Comment by katrinajaneczko** [comment]
> The forms are shaping up nicely! Would definitely approve this portion of the PR.
> 
> However, the calendar page seems a little buggy. If I click a button corresponding to a specific day it crashes the whole site. Also, if it's only buttons in the react component, I might suggest we instead use a bootstrap calendar instead and list the task titles. They look really nice and clean, and are consistent with our other forms. I humbly request that we remove this for now and give this creating the calendar it's own ticket.
> 
> https://mdbootstrap.com/docs/standard/plugins/calendar/

Whoops! I appreciate you commenting on this. I actually did not mean to include this piece in my PR, that was a mistake on my part. I will remove this portion and then take Christine's suggestion to center the form fields.

**Comment by Alexander-Russakoff** [comment]
I had a feeling that was the case since it wasn't in the PR note. Thank you for addressing it.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Katrina Janeczko ***@***.***>
Sent: Monday, March 27, 2023 11:58:02 AM
To: Capstone-Projects-2023-Spring/project-virtual-pet ***@***.***>
Cc: Alexander Russakoff ***@***.***>; Comment ***@***.***>
Subject: [External] Re: [Capstone-Projects-2023-Spring/project-virtual-pet] CSS for account and pet profile pages, SB-45 edit (PR #67)


The forms are shaping up nicely! Would definitely approve this portion of the PR.

However, the calendar page seems a little buggy. If I click a button corresponding to a specific day it crashes the whole site. Also, if it's only buttons in the react component, I might suggest we instead use a bootstrap calendar instead and list the task titles. They look really nice and clean, and are consistent with our other forms. I humbly request that we remove this for now and give this creating the calendar it's own ticket.

https://mdbootstrap.com/docs/standard/plugins/calendar/<https://nam10.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmdbootstrap.com%2Fdocs%2Fstandard%2Fplugins%2Fcalendar%2F&data=05%7C01%7Calexander.russakoff%40temple.edu%7Cd27a4120d4b04eec85d008db2edc0c3e%7C716e81efb52244738e3110bd02ccf6e5%7C0%7C0%7C638155294854626372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=2NfWTq5DgQq40rw41WD4LqBRfpky7olM3uPXvBu9A%2Fo%3D&reserved=0>

Whoops! I appreciate you commenting on this. I actually did not mean to include this piece in my PR, that was a mistake on my part. I will remove this portion and then take Christine's suggestion to center the form fields.

**Review by Alexander-Russakoff — APPROVED** [review]

**Comment by Alexander-Russakoff** [comment]
Thank you for addressing

**Pull request merged**
