### PR TITLE
Add candy pixel art

### PR DESCRIPTION
**Pull request by mgclay**
Sizes small and medium, all 5 tiers for each. These are scaled up using an online tool; resizing is subject to change.

### CODE REVIEW

**Review by Alexander-Russakoff — APPROVED** [review]
These look excellent! No notes.

**Review by harrisonfedor — APPROVED** [review]
these all look great!

**Comment by jay-newman** [comment]
These look awesome. Can we add these to a separate folder in images named candy?

**Review by jay-newman — APPROVED** [review]

**Comment by mgclay** [comment]
I'll close this PR and make a new one with the separate folder, and also add the size large candies (CAKE)

**Pull request closed without merging**
